package ExceptionHandling;

public class tryCatchpractice3 {
public static void main(String[] args) {

	
	catch(Exception e) {
		System.out.println("please try to access value within the range");
		System.out.println("hello");
	}
	
	finally {
		System.out.println("hi");
	}
	System.out.println("after finally");
	
}
}
