package ExceptionHandling;

public class tryCatchpractice2 {
public static void main(String[] args) {
	try {
		int a[]= {10,20,30,40};
		System.out.println(a[5]);
	}
	
	
	finally{
	
	System.out.println("hi");
	
}	
  System.out.println("after finally");	
}
}
